services:
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: tinypay
      MYSQL_USER: tinypay
      MYSQL_PASSWORD: tinypay
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - local-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  local-mysql-data:
